//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactDirectory.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Contact
    {
        public int ContactID { get; set; }

        [Required(ErrorMessage="Please select or enter Company name")]
        [StringLength(60)]//Set max length for company
        public string Company { get; set; }

         
       [StringLength(15)]//set max length for First name
        [Required(ErrorMessage = "Please enter First name")]
        public string FirstName { get; set; }
        
         
         //[Range(1,15,ErrorMessage="Last Name is too large or too small")]
         
         [Required(ErrorMessage="Please enter last name")]
         [StringLength(15)]
         public string LastName { get; set; }

        // [Range(5, 20,ErrorMessage="Job Title is too large or too small")]
         [Required(ErrorMessage = "Please enter Job Title")]
         [StringLength(50)]
         public string JobTitle { get; set; }

      
        [DataType(DataType.PhoneNumber)]
        [Required(ErrorMessage = "Please enter Office Phone number")]
             //[DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{#-###-###-####}")]
         [StringLength(14)]//string used for datatype because phone number overflows the range of integer
            //we can add more functionality to restrict it to a specific format
            public string OfficePhone { get; set; }

         
            [Required(ErrorMessage = "Please enter Cell Phone number")]
            [DataType(DataType.PhoneNumber)]
        
            [StringLength(14)] //string used for datatype because phone number overflows the range of integer
        //we can add more functionality to restrict it to a specific format
             public string CellPhone { get; set; }

           [Required(ErrorMessage = "Please enter fax number")]
            [StringLength(14)] //string used for datatype because fax number overflows the range of integer
            public string FaxNo { get; set; }

            [Required(ErrorMessage = "Please enter Email Address")]
            [DataType(DataType.EmailAddress)]
            [StringLength(40)]
            public string Email { get; set; }

        // [Range(5,20,ErrorMessage="Website name too large!")]
         [Required(ErrorMessage = "Please enter website")]
         [StringLength(40)]
         public string Website { get; set; }

         [Required(ErrorMessage = "Please enter Office address")]
         [StringLength(60)]
        public string Address { get; set; }
    }
}
